FROM node:16.14.2
WORKDIR /app
COPY ./package.json ./
RUN npm config set fetch-retry-mintimeout 20000
RUN npm config set fetch-retry-maxtimeout 120000
RUN npm i --legacy-peer-deps
COPY . .
CMD ["npm", "run", "start"]