POST http://localhost:3080/portfolio
content-type: application/json

{
    "title": "Portfolio teste",
    "description": "alguma descrição",
    "longDescription": "alguma descrição longa"
}

GET http://localhost:3080/portfolio
