@URL = http://localhost:3080/api/portfolio

###

POST {{URL}}
Content-type: application/json

{
    "title": "Portfolio teste",
    "description": "alguma descrição",
    "longDescription": "alguma descrição longa"
}

###

GET {{URL}}

###

GET http://localhost:3080/api/portfolio/portfolio-teste

###

PATCH http://localhost:3080/api/portfolio/portfolio-teste
Content-Type: application/json

{
    "title": "Realizando uma alteração no patch",
    "description": "A alteração foi realizada com sucesso?"
}

###

DELETE http://localhost:3080/api/portfolio/portfolio-segundo-teste